FileVersion = 1
LastConfig = "Debug"
LastPlatform = "Win64"
RecentFilesList = ["g:\\Projects\\raylib-SpaceGame\\src\\GameApp.bf", "g:\\BeefLang\\BeefLibs\\raylib-beef\\src\\Raylib.bf", "g:\\Projects\\raylib-SpaceGame\\src\\Textures.bf", "g:\\BeefLang\\BeefLibs\\corlib\\src\\String.bf"]

[MainWindow]
X = 1092
Y = 105
Width = 1200
Height = 1024
ShowKind = "Normal"

[MainDockingFrame]
Type = "DockingFrame"
SplitType = 2

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 400.0
RequestedHeight = 250.0
SizePriority = 250.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 250.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Workspace"
TabWidth = 112.0968
Type = "ProjectPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
IsFillWidget = true
Permanent = true
RequestedWidth = 150.0
RequestedHeight = 150.0
SizePriority = 150.0
DefaultDocumentsTabbedView = true
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "String.bf"
TabWidth = 77.58064
Type = "SourceViewPanel"
FilePath = "g:\\BeefLang\\BeefLibs\\corlib\\src\\String.bf"
CursorPos = 72504
VertPos = 59375.0
ProjectName = "corlib"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Textures.bf"
TabWidth = 89.67741
Type = "SourceViewPanel"
FilePath = "g:\\Projects\\raylib-SpaceGame\\src\\Textures.bf"
CursorPos = 1012
VertPos = 456.0
ProjectName = "SpaceGame"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "GameApp.bf"
TabWidth = 99.35484
Type = "SourceViewPanel"
FilePath = "g:\\Projects\\raylib-SpaceGame\\src\\GameApp.bf"
CursorPos = 703
VertPos = 483.5904
ProjectName = "SpaceGame"

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 312.0
RequestedHeight = 312.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 312.0
RequestedHeight = 312.0
SizePriority = 1612.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Memory"
TabWidth = 97.58064
Type = "MemoryPanel"
AutoResize = "Auto_Mul8"
RequestedWidth = 300.0

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Watch"
TabWidth = 85.48387
Type = "WatchPanel"
Columns = [{Width = 200.0}, {Width = 200.0}, {Width = 200.0}]
Items = [""]

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Auto"
TabWidth = 76.6129
Type = "AutoWatchPanel"
Columns = [{Width = 200.0}, {Width = 200.0}, {Width = 200.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 312.0
RequestedHeight = 312.0
SizePriority = 1612.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Threads"
TabWidth = 94.35484
Type = "ThreadPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Call Stack"
TabWidth = 104.0323
Type = "CallStackPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Immediate"
TabWidth = 109.6774
Type = "ImmediatePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Output"
TabWidth = 89.51613
Type = "OutputPanel"

[DebuggerDisplayTypes.""]
IntDisplayType = "Default"
MmDisplayType = "Default"
